config setup
    charondebug="ike 1, knl 1, cfg 0"
    uniqueids=no

conn expressway
    authby=secret
    type=tunnel
    keyexchange=ikev1
    left=10.10.14.77
    leftid=10.10.14.77
    leftsubnet=0.0.0.0/0
    leftauth=psk
    right=10.129.180.13
    rightid=ike@expressway.htb
    #rightsubnet=10.129.180.13/32
    rightsubnet=10.0.0.0/16
    rightauth=psk
    ike=3des-sha1-modp1024
    esp=3des-sha1
    auto=route
    aggressive=yes
    dpdaction=restart
    dpddelay=30s
    dpdtimeout=120s
